language: c

php:
    - 5.4
    - 5.5
    - 5.6

sudo: required
compiler:
    - gcc
os:
    - linux

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y php5-dev php5-cli
before_script: php -r 'try { $k = new Kafka("localhost:9092", [Kafka::LOGLEVEL => 123]); } catch (KafkaException $e) { var_dump($e->getMessage()); }'
script: ./travis.sh
