language: c

php:
    - 5.4
    - 5.5
    - 5.6

sudo: required
compiler:
    - gcc
os:
    - linux

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y php5-dev php5-cli
script: ./travis.sh
